### ISSUE TITLE
Request: Pet crits

### ISSUE THREAD

**Issue by Teax20** [Sven-Massard/SvensBamAddon#2]
Greetings,
would it be possible to add pet crits as bam option as well?
Or maybe tell me what do i need to change to get it for my own.

Btw, If someone in my group has a pet with my name, it triggers the bam sound aswell :)

Best regards

**Comment by Sven-Massard** [comment]
Hi, I might add it soonish. And thanks for the bug report. I've just started playing the new expansion and thus will start updating my addon again, until I stop playing...

**Comment by Teax20** [comment]
Alright thanks for your effort. Take your time :) Im playing on SoD right now, TWW does not interest me sadly :D

**Comment by Sven-Massard** [comment]
I did some fixes and added pet crits. I might polish it some more. I don't have a pet class on classic unfortunately, so I can only test on retail.
I added the new version to the alpha channel.

**Comment by Teax20** [comment]
Thanks for the fast response and added feature :D 
Did test it a bit and so far no errors and works as intended :)
Thanks
